### ISSUE TITLE
declare: -A: invalid option

### ISSUE THREAD

**Issue by pathawks** [lbarchive/-#1]
On Mac OS X, I keep getting this error:

``` text
-: line 25: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by livibetter** [comment]
I don't use OS X, but I am pretty sure you are using some default Bash version, which is pre-4.0, check with `bash --version`.

The `declare -A` is for associative arrays which is only supported since Bash 4.0.

Please confirm and update your Bash, if that's the case and I will close this as wontfix. I am not up to make `-` support pre-4.0, however, if anyone wants to submit a patch for that, I am not against as long as it doesn't get too complicated.

**Comment by pathawks** [comment]
``` text
~$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

You are right. Thanks for the info :+1:
